@echo off
:loop
echo Checking for network drives...
if exist G:\ (
    echo Network found! Starting sync...
    call "C:\Scripts\GandHSync\sync_all_drives.bat"
    echo Waiting 4 hours before next check...
    timeout /t 14400
) else (
    echo No network. Checking again in 5 minutes...
    timeout /t 300
)
goto :loop